import { getDb } from "@/lib/db";
import { NextResponse } from "next/server";

export interface SummaryRow {
    OWNR_ETP_CD: string;
    SKU: string;
    GATH_DE: string | null;
    GATH_DT: string | null;

    CA_STOCK: number;
    CA2_STOCK: number;
    GA_STOCK: number;
    GA2_STOCK: number;
    NJ_STOCK: number;
    SC_STOCK: number;
    TX_STOCK: number;
    WF_STOCK: number;
    TOTAL_STOCK: number;

    CA_INTRANSIT_STOCK: number;
    CA2_INTRANSIT_STOCK: number;
    GA_INTRANSIT_STOCK: number;
    GA2_INTRANSIT_STOCK: number;
    NJ_INTRANSIT_STOCK: number;
    SC_INTRANSIT_STOCK: number;
    TX_INTRANSIT_STOCK: number;
    WF_INTRANSIT_STOCK: number;
    TOTAL_INTRANSIT_STOCK: number;

    CA_CURR_YEAR_1WEEK_SALES_QTY: number;
    CA2_CURR_YEAR_1WEEK_SALES_QTY: number;
    GA_CURR_YEAR_1WEEK_SALES_QTY: number;
    GA2_CURR_YEAR_1WEEK_SALES_QTY: number;
    NJ_CURR_YEAR_1WEEK_SALES_QTY: number;
    SC_CURR_YEAR_1WEEK_SALES_QTY: number;
    TX_CURR_YEAR_1WEEK_SALES_QTY: number;
    WF_CURR_YEAR_1WEEK_SALES_QTY: number;
    CURR_YEAR_1WEEK_TOTAL_SALES_QTY: number;

    CA_LAST_YEAR_1WEEK_SALES_QTY: number;
    CA2_LAST_YEAR_1WEEK_SALES_QTY: number;
    GA_LAST_YEAR_1WEEK_SALES_QTY: number;
    GA2_LAST_YEAR_1WEEK_SALES_QTY: number;
    NJ_LAST_YEAR_1WEEK_SALES_QTY: number;
    SC_LAST_YEAR_1WEEK_SALES_QTY: number;
    TX_LAST_YEAR_1WEEK_SALES_QTY: number;
    WF_LAST_YEAR_1WEEK_SALES_QTY: number;
    LAST_YEAR_1WEEK_TOTAL_SALES_QTY: number;

    CA_CURR_YEAR_1MONTH_SALES_QTY: number;
    CA2_CURR_YEAR_1MONTH_SALES_QTY: number;
    GA_CURR_YEAR_1MONTH_SALES_QTY: number;
    GA2_CURR_YEAR_1MONTH_SALES_QTY: number;
    NJ_CURR_YEAR_1MONTH_SALES_QTY: number;
    SC_CURR_YEAR_1MONTH_SALES_QTY: number;
    TX_CURR_YEAR_1MONTH_SALES_QTY: number;
    WF_CURR_YEAR_1MONTH_SALES_QTY: number;
    CURR_YEAR_1MONTH_TOTAL_SALES_QTY: number;

    CA_LAST_YEAR_1MONTH_SALES_QTY: number;
    CA2_LAST_YEAR_1MONTH_SALES_QTY: number;
    GA_LAST_YEAR_1MONTH_SALES_QTY: number;
    GA2_LAST_YEAR_1MONTH_SALES_QTY: number;
    NJ_LAST_YEAR_1MONTH_SALES_QTY: number;
    SC_LAST_YEAR_1MONTH_SALES_QTY: number;
    TX_LAST_YEAR_1MONTH_SALES_QTY: number;
    WF_LAST_YEAR_1MONTH_SALES_QTY: number;
    LAST_YEAR_1MONTH_TOTAL_SALES_QTY: number;

    CA_CURR_YEAR_2MONTH_SALES_QTY: number;
    CA2_CURR_YEAR_2MONTH_SALES_QTY: number;
    GA_CURR_YEAR_2MONTH_SALES_QTY: number;
    GA2_CURR_YEAR_2MONTH_SALES_QTY: number;
    NJ_CURR_YEAR_2MONTH_SALES_QTY: number;
    SC_CURR_YEAR_2MONTH_SALES_QTY: number;
    TX_CURR_YEAR_2MONTH_SALES_QTY: number;
    WF_CURR_YEAR_2MONTH_SALES_QTY: number;
    CURR_YEAR_2MONTH_TOTAL_SALES_QTY: number;

    CA_LAST_YEAR_2MONTH_SALES_QTY: number;
    CA2_LAST_YEAR_2MONTH_SALES_QTY: number;
    GA_LAST_YEAR_2MONTH_SALES_QTY: number;
    GA2_LAST_YEAR_2MONTH_SALES_QTY: number;
    NJ_LAST_YEAR_2MONTH_SALES_QTY: number;
    SC_LAST_YEAR_2MONTH_SALES_QTY: number;
    TX_LAST_YEAR_2MONTH_SALES_QTY: number;
    WF_LAST_YEAR_2MONTH_SALES_QTY: number;
    LAST_YEAR_2MONTH_TOTAL_SALES_QTY: number;

    CA_LAST_YEAR_ACTL_SALES_QTY: number;
    CA2_LAST_YEAR_ACTL_SALES_QTY: number;
    GA_LAST_YEAR_ACTL_SALES_QTY: number;
    GA2_LAST_YEAR_ACTL_SALES_QTY: number;
    NJ_LAST_YEAR_ACTL_SALES_QTY: number;
    SC_LAST_YEAR_ACTL_SALES_QTY: number;
    TX_LAST_YEAR_ACTL_SALES_QTY: number;
    WF_LAST_YEAR_ACTL_SALES_QTY: number;
    LAST_YEAR_ACTL_SALES_QTY: number;

    CA1_SHIPPLAN_QTY: number;
    CA_SHIPPLAN_QTY: number;
    CA2_SHIPPLAN_QTY: number;
    GA_SHIPPLAN_QTY: number;
    GA2_SHIPPLAN_QTY: number;
    NJ_SHIPPLAN_QTY: number;
    SC_SHIPPLAN_QTY: number;
    TX_SHIPPLAN_QTY: number;
    WF_SHIPPLAN_QTY: number;
}

const SUMMARY_QUERY = `
    WITH all_skus AS (
        SELECT DISTINCT SKU
        FROM [HGBC].[RPA].[TB_SALES_STOCK_SUMMARY]
        WHERE GATH_DE = (SELECT MAX(GATH_DE) FROM [HGBC].[RPA].[TB_SALES_STOCK_SUMMARY])

        UNION

        SELECT DISTINCT ITM_ID AS SKU
        FROM [HGBC].[RPA].[TB_SHIPPING_PLAN_STOCK]
    )
    SELECT
        ISNULL(s.OWNR_ETP_CD, '')       AS OWNR_ETP_CD,
        a.SKU,
        s.GATH_DE,
        s.GATH_DT,

        ISNULL(s.CA_STOCK,  0)          AS CA_STOCK,
        ISNULL(s.CA2_STOCK, 0)          AS CA2_STOCK,
        ISNULL(s.GA_STOCK,  0)          AS GA_STOCK,
        ISNULL(s.GA2_STOCK, 0)          AS GA2_STOCK,
        ISNULL(s.NJ_STOCK,  0)          AS NJ_STOCK,
        ISNULL(s.SC_STOCK,  0)          AS SC_STOCK,
        ISNULL(s.TX_STOCK,  0)          AS TX_STOCK,
        ISNULL(s.WF_STOCK,  0)          AS WF_STOCK,
        ISNULL(s.TOTAL_STOCK, 0)        AS TOTAL_STOCK,

        ISNULL(s.CA_INTRANSIT_STOCK,    0) AS CA_INTRANSIT_STOCK,
        ISNULL(s.CA2_INTRANSIT_STOCK,   0) AS CA2_INTRANSIT_STOCK,
        ISNULL(s.GA_INTRANSIT_STOCK,    0) AS GA_INTRANSIT_STOCK,
        ISNULL(s.GA2_INTRANSIT_STOCK,   0) AS GA2_INTRANSIT_STOCK,
        ISNULL(s.NJ_INTRANSIT_STOCK,    0) AS NJ_INTRANSIT_STOCK,
        ISNULL(s.SC_INTRANSIT_STOCK,    0) AS SC_INTRANSIT_STOCK,
        ISNULL(s.TX_INTRANSIT_STOCK,    0) AS TX_INTRANSIT_STOCK,
        ISNULL(s.WF_INTRANSIT_STOCK,    0) AS WF_INTRANSIT_STOCK,
        ISNULL(s.TOTAL_INTRANSIT_STOCK, 0) AS TOTAL_INTRANSIT_STOCK,

        ISNULL(s.CA_CURR_YEAR_1WEEK_SALES_QTY,  0) AS CA_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.CA2_CURR_YEAR_1WEEK_SALES_QTY, 0) AS CA2_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.GA_CURR_YEAR_1WEEK_SALES_QTY,  0) AS GA_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.GA2_CURR_YEAR_1WEEK_SALES_QTY, 0) AS GA2_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.NJ_CURR_YEAR_1WEEK_SALES_QTY,  0) AS NJ_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.SC_CURR_YEAR_1WEEK_SALES_QTY,  0) AS SC_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.TX_CURR_YEAR_1WEEK_SALES_QTY,  0) AS TX_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.WF_CURR_YEAR_1WEEK_SALES_QTY,  0) AS WF_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.CURR_YEAR_1WEEK_TOTAL_SALES_QTY, 0) AS CURR_YEAR_1WEEK_TOTAL_SALES_QTY,

        ISNULL(s.CA_LAST_YEAR_1WEEK_SALES_QTY,  0) AS CA_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.CA2_LAST_YEAR_1WEEK_SALES_QTY, 0) AS CA2_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.GA_LAST_YEAR_1WEEK_SALES_QTY,  0) AS GA_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.GA2_LAST_YEAR_1WEEK_SALES_QTY, 0) AS GA2_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.NJ_LAST_YEAR_1WEEK_SALES_QTY,  0) AS NJ_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.SC_LAST_YEAR_1WEEK_SALES_QTY,  0) AS SC_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.TX_LAST_YEAR_1WEEK_SALES_QTY,  0) AS TX_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.WF_LAST_YEAR_1WEEK_SALES_QTY,  0) AS WF_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.LAST_YEAR_1WEEK_TOTAL_SALES_QTY, 0) AS LAST_YEAR_1WEEK_TOTAL_SALES_QTY,

        ISNULL(s.CA_CURR_YEAR_1MONTH_SALES_QTY,  0) AS CA_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.CA2_CURR_YEAR_1MONTH_SALES_QTY, 0) AS CA2_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.GA_CURR_YEAR_1MONTH_SALES_QTY,  0) AS GA_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.GA2_CURR_YEAR_1MONTH_SALES_QTY, 0) AS GA2_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.NJ_CURR_YEAR_1MONTH_SALES_QTY,  0) AS NJ_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.SC_CURR_YEAR_1MONTH_SALES_QTY,  0) AS SC_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.TX_CURR_YEAR_1MONTH_SALES_QTY,  0) AS TX_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.WF_CURR_YEAR_1MONTH_SALES_QTY,  0) AS WF_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.CURR_YEAR_1MONTH_TOTAL_SALES_QTY, 0) AS CURR_YEAR_1MONTH_TOTAL_SALES_QTY,

        ISNULL(s.CA_LAST_YEAR_1MONTH_SALES_QTY,  0) AS CA_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.CA2_LAST_YEAR_1MONTH_SALES_QTY, 0) AS CA2_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.GA_LAST_YEAR_1MONTH_SALES_QTY,  0) AS GA_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.GA2_LAST_YEAR_1MONTH_SALES_QTY, 0) AS GA2_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.NJ_LAST_YEAR_1MONTH_SALES_QTY,  0) AS NJ_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.SC_LAST_YEAR_1MONTH_SALES_QTY,  0) AS SC_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.TX_LAST_YEAR_1MONTH_SALES_QTY,  0) AS TX_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.WF_LAST_YEAR_1MONTH_SALES_QTY,  0) AS WF_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.LAST_YEAR_1MONTH_TOTAL_SALES_QTY, 0) AS LAST_YEAR_1MONTH_TOTAL_SALES_QTY,

        ISNULL(s.CA_CURR_YEAR_2MONTH_SALES_QTY,  0) AS CA_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.CA2_CURR_YEAR_2MONTH_SALES_QTY, 0) AS CA2_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.GA_CURR_YEAR_2MONTH_SALES_QTY,  0) AS GA_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.GA2_CURR_YEAR_2MONTH_SALES_QTY, 0) AS GA2_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.NJ_CURR_YEAR_2MONTH_SALES_QTY,  0) AS NJ_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.SC_CURR_YEAR_2MONTH_SALES_QTY,  0) AS SC_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.TX_CURR_YEAR_2MONTH_SALES_QTY,  0) AS TX_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.WF_CURR_YEAR_2MONTH_SALES_QTY,  0) AS WF_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.CURR_YEAR_2MONTH_TOTAL_SALES_QTY, 0) AS CURR_YEAR_2MONTH_TOTAL_SALES_QTY,

        ISNULL(s.CA_LAST_YEAR_2MONTH_SALES_QTY,  0) AS CA_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.CA2_LAST_YEAR_2MONTH_SALES_QTY, 0) AS CA2_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.GA_LAST_YEAR_2MONTH_SALES_QTY,  0) AS GA_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.GA2_LAST_YEAR_2MONTH_SALES_QTY, 0) AS GA2_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.NJ_LAST_YEAR_2MONTH_SALES_QTY,  0) AS NJ_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.SC_LAST_YEAR_2MONTH_SALES_QTY,  0) AS SC_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.TX_LAST_YEAR_2MONTH_SALES_QTY,  0) AS TX_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.WF_LAST_YEAR_2MONTH_SALES_QTY,  0) AS WF_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.LAST_YEAR_2MONTH_TOTAL_SALES_QTY, 0) AS LAST_YEAR_2MONTH_TOTAL_SALES_QTY,

        ISNULL(s.CA_LAST_YEAR_ACTL_SALES_QTY,  0) AS CA_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.CA2_LAST_YEAR_ACTL_SALES_QTY, 0) AS CA2_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.GA_LAST_YEAR_ACTL_SALES_QTY,  0) AS GA_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.GA2_LAST_YEAR_ACTL_SALES_QTY, 0) AS GA2_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.NJ_LAST_YEAR_ACTL_SALES_QTY,  0) AS NJ_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.SC_LAST_YEAR_ACTL_SALES_QTY,  0) AS SC_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.TX_LAST_YEAR_ACTL_SALES_QTY,  0) AS TX_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.WF_LAST_YEAR_ACTL_SALES_QTY,  0) AS WF_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.LAST_YEAR_ACTL_SALES_QTY,     0) AS LAST_YEAR_ACTL_SALES_QTY,

        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14361 THEN p.QTY END), 0) AS CA1_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14630 THEN p.QTY END), 0) AS CA_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14631 THEN p.QTY END), 0) AS CA2_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14632 THEN p.QTY END), 0) AS GA_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14633 THEN p.QTY END), 0) AS GA2_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14634 THEN p.QTY END), 0) AS NJ_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14635 THEN p.QTY END), 0) AS SC_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14636 THEN p.QTY END), 0) AS TX_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 0     THEN p.QTY END), 0) AS WF_SHIPPLAN_QTY

    FROM all_skus a
    LEFT JOIN [HGBC].[RPA].[TB_SALES_STOCK_SUMMARY] s
        ON a.SKU = s.SKU
        AND s.GATH_DE = (SELECT MAX(GATH_DE) FROM [HGBC].[RPA].[TB_SALES_STOCK_SUMMARY])
    LEFT JOIN [HGBC].[RPA].[TB_SHIPPING_PLAN_STOCK] p
        ON a.SKU = p.ITM_ID

    GROUP BY
        s.OWNR_ETP_CD, a.SKU, s.GATH_DE, s.GATH_DT,
        s.CA_STOCK, s.CA2_STOCK, s.GA_STOCK, s.GA2_STOCK,
        s.NJ_STOCK, s.SC_STOCK, s.TX_STOCK, s.WF_STOCK, s.TOTAL_STOCK,
        s.CA_INTRANSIT_STOCK, s.CA2_INTRANSIT_STOCK, s.GA_INTRANSIT_STOCK, s.GA2_INTRANSIT_STOCK,
        s.NJ_INTRANSIT_STOCK, s.SC_INTRANSIT_STOCK, s.TX_INTRANSIT_STOCK, s.WF_INTRANSIT_STOCK,
        s.TOTAL_INTRANSIT_STOCK,
        s.CA_CURR_YEAR_1WEEK_SALES_QTY, s.CA2_CURR_YEAR_1WEEK_SALES_QTY,
        s.GA_CURR_YEAR_1WEEK_SALES_QTY, s.GA2_CURR_YEAR_1WEEK_SALES_QTY,
        s.NJ_CURR_YEAR_1WEEK_SALES_QTY, s.SC_CURR_YEAR_1WEEK_SALES_QTY,
        s.TX_CURR_YEAR_1WEEK_SALES_QTY, s.WF_CURR_YEAR_1WEEK_SALES_QTY,
        s.CURR_YEAR_1WEEK_TOTAL_SALES_QTY,
        s.CA_LAST_YEAR_1WEEK_SALES_QTY, s.CA2_LAST_YEAR_1WEEK_SALES_QTY,
        s.GA_LAST_YEAR_1WEEK_SALES_QTY, s.GA2_LAST_YEAR_1WEEK_SALES_QTY,
        s.NJ_LAST_YEAR_1WEEK_SALES_QTY, s.SC_LAST_YEAR_1WEEK_SALES_QTY,
        s.TX_LAST_YEAR_1WEEK_SALES_QTY, s.WF_LAST_YEAR_1WEEK_SALES_QTY,
        s.LAST_YEAR_1WEEK_TOTAL_SALES_QTY,
        s.CA_CURR_YEAR_1MONTH_SALES_QTY, s.CA2_CURR_YEAR_1MONTH_SALES_QTY,
        s.GA_CURR_YEAR_1MONTH_SALES_QTY, s.GA2_CURR_YEAR_1MONTH_SALES_QTY,
        s.NJ_CURR_YEAR_1MONTH_SALES_QTY, s.SC_CURR_YEAR_1MONTH_SALES_QTY,
        s.TX_CURR_YEAR_1MONTH_SALES_QTY, s.WF_CURR_YEAR_1MONTH_SALES_QTY,
        s.CURR_YEAR_1MONTH_TOTAL_SALES_QTY,
        s.CA_LAST_YEAR_1MONTH_SALES_QTY, s.CA2_LAST_YEAR_1MONTH_SALES_QTY,
        s.GA_LAST_YEAR_1MONTH_SALES_QTY, s.GA2_LAST_YEAR_1MONTH_SALES_QTY,
        s.NJ_LAST_YEAR_1MONTH_SALES_QTY, s.SC_LAST_YEAR_1MONTH_SALES_QTY,
        s.TX_LAST_YEAR_1MONTH_SALES_QTY, s.WF_LAST_YEAR_1MONTH_SALES_QTY,
        s.LAST_YEAR_1MONTH_TOTAL_SALES_QTY,
        s.CA_CURR_YEAR_2MONTH_SALES_QTY, s.CA2_CURR_YEAR_2MONTH_SALES_QTY,
        s.GA_CURR_YEAR_2MONTH_SALES_QTY, s.GA2_CURR_YEAR_2MONTH_SALES_QTY,
        s.NJ_CURR_YEAR_2MONTH_SALES_QTY, s.SC_CURR_YEAR_2MONTH_SALES_QTY,
        s.TX_CURR_YEAR_2MONTH_SALES_QTY, s.WF_CURR_YEAR_2MONTH_SALES_QTY,
        s.CURR_YEAR_2MONTH_TOTAL_SALES_QTY,
        s.CA_LAST_YEAR_2MONTH_SALES_QTY, s.CA2_LAST_YEAR_2MONTH_SALES_QTY,
        s.GA_LAST_YEAR_2MONTH_SALES_QTY, s.GA2_LAST_YEAR_2MONTH_SALES_QTY,
        s.NJ_LAST_YEAR_2MONTH_SALES_QTY, s.SC_LAST_YEAR_2MONTH_SALES_QTY,
        s.TX_LAST_YEAR_2MONTH_SALES_QTY, s.WF_LAST_YEAR_2MONTH_SALES_QTY,
        s.LAST_YEAR_2MONTH_TOTAL_SALES_QTY,
        s.CA_LAST_YEAR_ACTL_SALES_QTY, s.CA2_LAST_YEAR_ACTL_SALES_QTY,
        s.GA_LAST_YEAR_ACTL_SALES_QTY, s.GA2_LAST_YEAR_ACTL_SALES_QTY,
        s.NJ_LAST_YEAR_ACTL_SALES_QTY, s.SC_LAST_YEAR_ACTL_SALES_QTY,
        s.TX_LAST_YEAR_ACTL_SALES_QTY, s.WF_LAST_YEAR_ACTL_SALES_QTY,
        s.LAST_YEAR_ACTL_SALES_QTY
`;

export async function GET() {
    try {
        const db = await getDb();
        const result = await db.request().query<SummaryRow>(SUMMARY_QUERY);

        const rows = result.recordset;
        // rows[0]이 TB_SHIPPING_PLAN_STOCK에만 존재하는 SKU면 LEFT JOIN으로 GATH_DT가 NULL이 될 수 있으므로
        // 첫 번째 non-null 값을 찾는다.
        const snapshotDate = rows.find((r) => r.GATH_DT)?.GATH_DT ?? null;

        console.log(`DB 조회: ${rows.length}개 SKU (기준일: ${snapshotDate})`);

        return NextResponse.json({
            success: true,
            data: rows,
            snapshotDate,
        });
    } catch (err) {
        console.error("DB 조회 오류:", err);
        return NextResponse.json(
            { success: false, error: String(err) },
            { status: 500 }
        );
    }
}