import { getDb } from "@/lib/db";
import { NextResponse } from "next/server";
import sql from "mssql";

export interface SummaryRow {
    OWNR_ETP_CD: string;
    SKU: string;
    GATH_DE: string | null;
    GATH_DT: string | null;

    CA_STOCK: number;
    CA2_STOCK: number;
    GA_STOCK: number;
    GA2_STOCK: number;
    NJ_STOCK: number;
    SC_STOCK: number;
    TX_STOCK: number;
    WF_STOCK: number;
    TOTAL_STOCK: number;

    CA_INTRANSIT_STOCK: number;
    CA2_INTRANSIT_STOCK: number;
    GA_INTRANSIT_STOCK: number;
    GA2_INTRANSIT_STOCK: number;
    NJ_INTRANSIT_STOCK: number;
    SC_INTRANSIT_STOCK: number;
    TX_INTRANSIT_STOCK: number;
    WF_INTRANSIT_STOCK: number;
    TOTAL_INTRANSIT_STOCK: number;

    CA_CURR_YEAR_1WEEK_SALES_QTY: number;
    CA2_CURR_YEAR_1WEEK_SALES_QTY: number;
    GA_CURR_YEAR_1WEEK_SALES_QTY: number;
    GA2_CURR_YEAR_1WEEK_SALES_QTY: number;
    NJ_CURR_YEAR_1WEEK_SALES_QTY: number;
    SC_CURR_YEAR_1WEEK_SALES_QTY: number;
    TX_CURR_YEAR_1WEEK_SALES_QTY: number;
    WF_CURR_YEAR_1WEEK_SALES_QTY: number;
    CURR_YEAR_1WEEK_TOTAL_SALES_QTY: number;

    CA_LAST_YEAR_1WEEK_SALES_QTY: number;
    CA2_LAST_YEAR_1WEEK_SALES_QTY: number;
    GA_LAST_YEAR_1WEEK_SALES_QTY: number;
    GA2_LAST_YEAR_1WEEK_SALES_QTY: number;
    NJ_LAST_YEAR_1WEEK_SALES_QTY: number;
    SC_LAST_YEAR_1WEEK_SALES_QTY: number;
    TX_LAST_YEAR_1WEEK_SALES_QTY: number;
    WF_LAST_YEAR_1WEEK_SALES_QTY: number;
    LAST_YEAR_1WEEK_TOTAL_SALES_QTY: number;

    CA_CURR_YEAR_1MONTH_SALES_QTY: number;
    CA2_CURR_YEAR_1MONTH_SALES_QTY: number;
    GA_CURR_YEAR_1MONTH_SALES_QTY: number;
    GA2_CURR_YEAR_1MONTH_SALES_QTY: number;
    NJ_CURR_YEAR_1MONTH_SALES_QTY: number;
    SC_CURR_YEAR_1MONTH_SALES_QTY: number;
    TX_CURR_YEAR_1MONTH_SALES_QTY: number;
    WF_CURR_YEAR_1MONTH_SALES_QTY: number;
    CURR_YEAR_1MONTH_TOTAL_SALES_QTY: number;

    CA_LAST_YEAR_1MONTH_SALES_QTY: number;
    CA2_LAST_YEAR_1MONTH_SALES_QTY: number;
    GA_LAST_YEAR_1MONTH_SALES_QTY: number;
    GA2_LAST_YEAR_1MONTH_SALES_QTY: number;
    NJ_LAST_YEAR_1MONTH_SALES_QTY: number;
    SC_LAST_YEAR_1MONTH_SALES_QTY: number;
    TX_LAST_YEAR_1MONTH_SALES_QTY: number;
    WF_LAST_YEAR_1MONTH_SALES_QTY: number;
    LAST_YEAR_1MONTH_TOTAL_SALES_QTY: number;

    CA_CURR_YEAR_2MONTH_SALES_QTY: number;
    CA2_CURR_YEAR_2MONTH_SALES_QTY: number;
    GA_CURR_YEAR_2MONTH_SALES_QTY: number;
    GA2_CURR_YEAR_2MONTH_SALES_QTY: number;
    NJ_CURR_YEAR_2MONTH_SALES_QTY: number;
    SC_CURR_YEAR_2MONTH_SALES_QTY: number;
    TX_CURR_YEAR_2MONTH_SALES_QTY: number;
    WF_CURR_YEAR_2MONTH_SALES_QTY: number;
    CURR_YEAR_2MONTH_TOTAL_SALES_QTY: number;

    CA_LAST_YEAR_2MONTH_SALES_QTY: number;
    CA2_LAST_YEAR_2MONTH_SALES_QTY: number;
    GA_LAST_YEAR_2MONTH_SALES_QTY: number;
    GA2_LAST_YEAR_2MONTH_SALES_QTY: number;
    NJ_LAST_YEAR_2MONTH_SALES_QTY: number;
    SC_LAST_YEAR_2MONTH_SALES_QTY: number;
    TX_LAST_YEAR_2MONTH_SALES_QTY: number;
    WF_LAST_YEAR_2MONTH_SALES_QTY: number;
    LAST_YEAR_2MONTH_TOTAL_SALES_QTY: number;

    CA_LAST_YEAR_ACTL_SALES_QTY: number;
    CA2_LAST_YEAR_ACTL_SALES_QTY: number;
    GA_LAST_YEAR_ACTL_SALES_QTY: number;
    GA2_LAST_YEAR_ACTL_SALES_QTY: number;
    NJ_LAST_YEAR_ACTL_SALES_QTY: number;
    SC_LAST_YEAR_ACTL_SALES_QTY: number;
    TX_LAST_YEAR_ACTL_SALES_QTY: number;
    WF_LAST_YEAR_ACTL_SALES_QTY: number;
    LAST_YEAR_ACTL_SALES_QTY: number;

    CA1_SHIPPLAN_QTY: number;
    CA_SHIPPLAN_QTY: number;
    CA2_SHIPPLAN_QTY: number;
    GA_SHIPPLAN_QTY: number;
    GA2_SHIPPLAN_QTY: number;
    NJ_SHIPPLAN_QTY: number;
    SC_SHIPPLAN_QTY: number;
    TX_SHIPPLAN_QTY: number;
    WF_SHIPPLAN_QTY: number;
}

/** SKU별 최근 84일(PST) 실제 CA/TX/NJ/GA 창고 출고 비율 (합계 = 1). */
export type ShipRatio84d = {
    CA: number;
    TX: number;
    NJ: number;
    GA: number;
};

type WhShipRow = {
    SKU: string;
    CA_QTY: number;
    TX_QTY: number;
    NJ_QTY: number;
    GA_QTY: number;
};

//출고 비율 쿼리
const WH_SHIP_84D_QUERY = `
    SELECT
        pg.INVT_SKU AS SKU,
        SUM(CASE WHEN o.WAREHOUSE IN ('14630', '14631') THEN o.QTY ELSE 0 END) AS CA_QTY,
        SUM(CASE WHEN o.WAREHOUSE = '14636' THEN o.QTY ELSE 0 END) AS TX_QTY,
        SUM(CASE WHEN o.WAREHOUSE = '14634' THEN o.QTY ELSE 0 END) AS NJ_QTY,
        SUM(CASE WHEN o.WAREHOUSE IN ('14632', '14633', '14635') THEN o.QTY ELSE 0 END) AS GA_QTY
    FROM [HGBC].[SD].[TB_ORD_DAIL] o
    JOIN [HGBC].[SD].[TB_PROD_GROUP] pg ON o.ITM_ID = pg.ITM_ID
    WHERE o.ORD_DE >= @cutoffDate
      AND pg.INVT_SKU <> ''
      AND o.WAREHOUSE IN ('14630', '14631', '14632', '14633', '14634', '14635', '14636')
    GROUP BY pg.INVT_SKU
`;

/** 오늘(PST) 기준 daysAgo일 전 00:00:00(PST) 문자열을 반환한다. */
function getPstCutoffDate(daysAgo: number): string {
    const pstNow = new Date(new Date().toLocaleString("en-US", { timeZone: "America/Los_Angeles" }));
    pstNow.setDate(pstNow.getDate() - daysAgo);
    const y = pstNow.getFullYear();
    const m = String(pstNow.getMonth() + 1).padStart(2, "0");
    const d = String(pstNow.getDate()).padStart(2, "0");
    return `${y}-${m}-${d} 00:00:00`;
}

//SUMMARY QUERY
const SUMMARY_QUERY = `
    WITH all_skus AS (
        SELECT DISTINCT SKU
        FROM [HGBC].[RPA].[TB_SALES_STOCK_SUMMARY]
        WHERE GATH_DE = (SELECT MAX(GATH_DE) FROM [HGBC].[RPA].[TB_SALES_STOCK_SUMMARY])

        UNION

        SELECT DISTINCT ITM_ID AS SKU
        FROM [HGBC].[RPA].[TB_SHIPPING_PLAN_STOCK]
    )
    SELECT
        ISNULL(s.OWNR_ETP_CD, '')       AS OWNR_ETP_CD,
        a.SKU,
        s.GATH_DE,
        s.GATH_DT,

        ISNULL(s.CA_STOCK,  0)          AS CA_STOCK,
        ISNULL(s.CA2_STOCK, 0)          AS CA2_STOCK,
        ISNULL(s.GA_STOCK,  0)          AS GA_STOCK,
        ISNULL(s.GA2_STOCK, 0)          AS GA2_STOCK,
        ISNULL(s.NJ_STOCK,  0)          AS NJ_STOCK,
        ISNULL(s.SC_STOCK,  0)          AS SC_STOCK,
        ISNULL(s.TX_STOCK,  0)          AS TX_STOCK,
        ISNULL(s.WF_STOCK,  0)          AS WF_STOCK,
        ISNULL(s.TOTAL_STOCK, 0)        AS TOTAL_STOCK,

        ISNULL(s.CA_INTRANSIT_STOCK,    0) AS CA_INTRANSIT_STOCK,
        ISNULL(s.CA2_INTRANSIT_STOCK,   0) AS CA2_INTRANSIT_STOCK,
        ISNULL(s.GA_INTRANSIT_STOCK,    0) AS GA_INTRANSIT_STOCK,
        ISNULL(s.GA2_INTRANSIT_STOCK,   0) AS GA2_INTRANSIT_STOCK,
        ISNULL(s.NJ_INTRANSIT_STOCK,    0) AS NJ_INTRANSIT_STOCK,
        ISNULL(s.SC_INTRANSIT_STOCK,    0) AS SC_INTRANSIT_STOCK,
        ISNULL(s.TX_INTRANSIT_STOCK,    0) AS TX_INTRANSIT_STOCK,
        ISNULL(s.WF_INTRANSIT_STOCK,    0) AS WF_INTRANSIT_STOCK,
        ISNULL(s.TOTAL_INTRANSIT_STOCK, 0) AS TOTAL_INTRANSIT_STOCK,

        ISNULL(s.CA_CURR_YEAR_1WEEK_SALES_QTY,  0) AS CA_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.CA2_CURR_YEAR_1WEEK_SALES_QTY, 0) AS CA2_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.GA_CURR_YEAR_1WEEK_SALES_QTY,  0) AS GA_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.GA2_CURR_YEAR_1WEEK_SALES_QTY, 0) AS GA2_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.NJ_CURR_YEAR_1WEEK_SALES_QTY,  0) AS NJ_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.SC_CURR_YEAR_1WEEK_SALES_QTY,  0) AS SC_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.TX_CURR_YEAR_1WEEK_SALES_QTY,  0) AS TX_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.WF_CURR_YEAR_1WEEK_SALES_QTY,  0) AS WF_CURR_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.CURR_YEAR_1WEEK_TOTAL_SALES_QTY, 0) AS CURR_YEAR_1WEEK_TOTAL_SALES_QTY,

        ISNULL(s.CA_LAST_YEAR_1WEEK_SALES_QTY,  0) AS CA_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.CA2_LAST_YEAR_1WEEK_SALES_QTY, 0) AS CA2_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.GA_LAST_YEAR_1WEEK_SALES_QTY,  0) AS GA_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.GA2_LAST_YEAR_1WEEK_SALES_QTY, 0) AS GA2_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.NJ_LAST_YEAR_1WEEK_SALES_QTY,  0) AS NJ_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.SC_LAST_YEAR_1WEEK_SALES_QTY,  0) AS SC_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.TX_LAST_YEAR_1WEEK_SALES_QTY,  0) AS TX_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.WF_LAST_YEAR_1WEEK_SALES_QTY,  0) AS WF_LAST_YEAR_1WEEK_SALES_QTY,
        ISNULL(s.LAST_YEAR_1WEEK_TOTAL_SALES_QTY, 0) AS LAST_YEAR_1WEEK_TOTAL_SALES_QTY,

        ISNULL(s.CA_CURR_YEAR_1MONTH_SALES_QTY,  0) AS CA_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.CA2_CURR_YEAR_1MONTH_SALES_QTY, 0) AS CA2_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.GA_CURR_YEAR_1MONTH_SALES_QTY,  0) AS GA_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.GA2_CURR_YEAR_1MONTH_SALES_QTY, 0) AS GA2_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.NJ_CURR_YEAR_1MONTH_SALES_QTY,  0) AS NJ_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.SC_CURR_YEAR_1MONTH_SALES_QTY,  0) AS SC_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.TX_CURR_YEAR_1MONTH_SALES_QTY,  0) AS TX_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.WF_CURR_YEAR_1MONTH_SALES_QTY,  0) AS WF_CURR_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.CURR_YEAR_1MONTH_TOTAL_SALES_QTY, 0) AS CURR_YEAR_1MONTH_TOTAL_SALES_QTY,

        ISNULL(s.CA_LAST_YEAR_1MONTH_SALES_QTY,  0) AS CA_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.CA2_LAST_YEAR_1MONTH_SALES_QTY, 0) AS CA2_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.GA_LAST_YEAR_1MONTH_SALES_QTY,  0) AS GA_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.GA2_LAST_YEAR_1MONTH_SALES_QTY, 0) AS GA2_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.NJ_LAST_YEAR_1MONTH_SALES_QTY,  0) AS NJ_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.SC_LAST_YEAR_1MONTH_SALES_QTY,  0) AS SC_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.TX_LAST_YEAR_1MONTH_SALES_QTY,  0) AS TX_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.WF_LAST_YEAR_1MONTH_SALES_QTY,  0) AS WF_LAST_YEAR_1MONTH_SALES_QTY,
        ISNULL(s.LAST_YEAR_1MONTH_TOTAL_SALES_QTY, 0) AS LAST_YEAR_1MONTH_TOTAL_SALES_QTY,

        ISNULL(s.CA_CURR_YEAR_2MONTH_SALES_QTY,  0) AS CA_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.CA2_CURR_YEAR_2MONTH_SALES_QTY, 0) AS CA2_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.GA_CURR_YEAR_2MONTH_SALES_QTY,  0) AS GA_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.GA2_CURR_YEAR_2MONTH_SALES_QTY, 0) AS GA2_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.NJ_CURR_YEAR_2MONTH_SALES_QTY,  0) AS NJ_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.SC_CURR_YEAR_2MONTH_SALES_QTY,  0) AS SC_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.TX_CURR_YEAR_2MONTH_SALES_QTY,  0) AS TX_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.WF_CURR_YEAR_2MONTH_SALES_QTY,  0) AS WF_CURR_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.CURR_YEAR_2MONTH_TOTAL_SALES_QTY, 0) AS CURR_YEAR_2MONTH_TOTAL_SALES_QTY,

        ISNULL(s.CA_LAST_YEAR_2MONTH_SALES_QTY,  0) AS CA_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.CA2_LAST_YEAR_2MONTH_SALES_QTY, 0) AS CA2_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.GA_LAST_YEAR_2MONTH_SALES_QTY,  0) AS GA_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.GA2_LAST_YEAR_2MONTH_SALES_QTY, 0) AS GA2_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.NJ_LAST_YEAR_2MONTH_SALES_QTY,  0) AS NJ_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.SC_LAST_YEAR_2MONTH_SALES_QTY,  0) AS SC_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.TX_LAST_YEAR_2MONTH_SALES_QTY,  0) AS TX_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.WF_LAST_YEAR_2MONTH_SALES_QTY,  0) AS WF_LAST_YEAR_2MONTH_SALES_QTY,
        ISNULL(s.LAST_YEAR_2MONTH_TOTAL_SALES_QTY, 0) AS LAST_YEAR_2MONTH_TOTAL_SALES_QTY,

        ISNULL(s.CA_LAST_YEAR_ACTL_SALES_QTY,  0) AS CA_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.CA2_LAST_YEAR_ACTL_SALES_QTY, 0) AS CA2_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.GA_LAST_YEAR_ACTL_SALES_QTY,  0) AS GA_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.GA2_LAST_YEAR_ACTL_SALES_QTY, 0) AS GA2_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.NJ_LAST_YEAR_ACTL_SALES_QTY,  0) AS NJ_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.SC_LAST_YEAR_ACTL_SALES_QTY,  0) AS SC_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.TX_LAST_YEAR_ACTL_SALES_QTY,  0) AS TX_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.WF_LAST_YEAR_ACTL_SALES_QTY,  0) AS WF_LAST_YEAR_ACTL_SALES_QTY,
        ISNULL(s.LAST_YEAR_ACTL_SALES_QTY,     0) AS LAST_YEAR_ACTL_SALES_QTY,

        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14361 THEN p.QTY END), 0) AS CA1_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14630 THEN p.QTY END), 0) AS CA_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14631 THEN p.QTY END), 0) AS CA2_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14632 THEN p.QTY END), 0) AS GA_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14633 THEN p.QTY END), 0) AS GA2_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14634 THEN p.QTY END), 0) AS NJ_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14635 THEN p.QTY END), 0) AS SC_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 14636 THEN p.QTY END), 0) AS TX_SHIPPLAN_QTY,
        ISNULL(SUM(CASE WHEN p.WRHS_NM = 0     THEN p.QTY END), 0) AS WF_SHIPPLAN_QTY

    FROM all_skus a
    LEFT JOIN [HGBC].[RPA].[TB_SALES_STOCK_SUMMARY] s
        ON a.SKU = s.SKU
        AND s.GATH_DE = (SELECT MAX(GATH_DE) FROM [HGBC].[RPA].[TB_SALES_STOCK_SUMMARY])
    LEFT JOIN [HGBC].[RPA].[TB_SHIPPING_PLAN_STOCK] p
        ON a.SKU = p.ITM_ID
        AND p.GATH_DE = (SELECT MAX(GATH_DE) FROM [HGBC].[RPA].[TB_SALES_STOCK_SUMMARY])

    GROUP BY
        s.OWNR_ETP_CD, a.SKU, s.GATH_DE, s.GATH_DT,
        s.CA_STOCK, s.CA2_STOCK, s.GA_STOCK, s.GA2_STOCK,
        s.NJ_STOCK, s.SC_STOCK, s.TX_STOCK, s.WF_STOCK, s.TOTAL_STOCK,
        s.CA_INTRANSIT_STOCK, s.CA2_INTRANSIT_STOCK, s.GA_INTRANSIT_STOCK, s.GA2_INTRANSIT_STOCK,
        s.NJ_INTRANSIT_STOCK, s.SC_INTRANSIT_STOCK, s.TX_INTRANSIT_STOCK, s.WF_INTRANSIT_STOCK,
        s.TOTAL_INTRANSIT_STOCK,
        s.CA_CURR_YEAR_1WEEK_SALES_QTY, s.CA2_CURR_YEAR_1WEEK_SALES_QTY,
        s.GA_CURR_YEAR_1WEEK_SALES_QTY, s.GA2_CURR_YEAR_1WEEK_SALES_QTY,
        s.NJ_CURR_YEAR_1WEEK_SALES_QTY, s.SC_CURR_YEAR_1WEEK_SALES_QTY,
        s.TX_CURR_YEAR_1WEEK_SALES_QTY, s.WF_CURR_YEAR_1WEEK_SALES_QTY,
        s.CURR_YEAR_1WEEK_TOTAL_SALES_QTY,
        s.CA_LAST_YEAR_1WEEK_SALES_QTY, s.CA2_LAST_YEAR_1WEEK_SALES_QTY,
        s.GA_LAST_YEAR_1WEEK_SALES_QTY, s.GA2_LAST_YEAR_1WEEK_SALES_QTY,
        s.NJ_LAST_YEAR_1WEEK_SALES_QTY, s.SC_LAST_YEAR_1WEEK_SALES_QTY,
        s.TX_LAST_YEAR_1WEEK_SALES_QTY, s.WF_LAST_YEAR_1WEEK_SALES_QTY,
        s.LAST_YEAR_1WEEK_TOTAL_SALES_QTY,
        s.CA_CURR_YEAR_1MONTH_SALES_QTY, s.CA2_CURR_YEAR_1MONTH_SALES_QTY,
        s.GA_CURR_YEAR_1MONTH_SALES_QTY, s.GA2_CURR_YEAR_1MONTH_SALES_QTY,
        s.NJ_CURR_YEAR_1MONTH_SALES_QTY, s.SC_CURR_YEAR_1MONTH_SALES_QTY,
        s.TX_CURR_YEAR_1MONTH_SALES_QTY, s.WF_CURR_YEAR_1MONTH_SALES_QTY,
        s.CURR_YEAR_1MONTH_TOTAL_SALES_QTY,
        s.CA_LAST_YEAR_1MONTH_SALES_QTY, s.CA2_LAST_YEAR_1MONTH_SALES_QTY,
        s.GA_LAST_YEAR_1MONTH_SALES_QTY, s.GA2_LAST_YEAR_1MONTH_SALES_QTY,
        s.NJ_LAST_YEAR_1MONTH_SALES_QTY, s.SC_LAST_YEAR_1MONTH_SALES_QTY,
        s.TX_LAST_YEAR_1MONTH_SALES_QTY, s.WF_LAST_YEAR_1MONTH_SALES_QTY,
        s.LAST_YEAR_1MONTH_TOTAL_SALES_QTY,
        s.CA_CURR_YEAR_2MONTH_SALES_QTY, s.CA2_CURR_YEAR_2MONTH_SALES_QTY,
        s.GA_CURR_YEAR_2MONTH_SALES_QTY, s.GA2_CURR_YEAR_2MONTH_SALES_QTY,
        s.NJ_CURR_YEAR_2MONTH_SALES_QTY, s.SC_CURR_YEAR_2MONTH_SALES_QTY,
        s.TX_CURR_YEAR_2MONTH_SALES_QTY, s.WF_CURR_YEAR_2MONTH_SALES_QTY,
        s.CURR_YEAR_2MONTH_TOTAL_SALES_QTY,
        s.CA_LAST_YEAR_2MONTH_SALES_QTY, s.CA2_LAST_YEAR_2MONTH_SALES_QTY,
        s.GA_LAST_YEAR_2MONTH_SALES_QTY, s.GA2_LAST_YEAR_2MONTH_SALES_QTY,
        s.NJ_LAST_YEAR_2MONTH_SALES_QTY, s.SC_LAST_YEAR_2MONTH_SALES_QTY,
        s.TX_LAST_YEAR_2MONTH_SALES_QTY, s.WF_LAST_YEAR_2MONTH_SALES_QTY,
        s.LAST_YEAR_2MONTH_TOTAL_SALES_QTY,
        s.CA_LAST_YEAR_ACTL_SALES_QTY, s.CA2_LAST_YEAR_ACTL_SALES_QTY,
        s.GA_LAST_YEAR_ACTL_SALES_QTY, s.GA2_LAST_YEAR_ACTL_SALES_QTY,
        s.NJ_LAST_YEAR_ACTL_SALES_QTY, s.SC_LAST_YEAR_ACTL_SALES_QTY,
        s.TX_LAST_YEAR_ACTL_SALES_QTY, s.WF_LAST_YEAR_ACTL_SALES_QTY,
        s.LAST_YEAR_ACTL_SALES_QTY
`;

export async function GET() {
    try {
        const db = await getDb();
        const result = await db.request().query<SummaryRow>(SUMMARY_QUERY);

        const rows = result.recordset;
        // rows[0]이 TB_SHIPPING_PLAN_STOCK에만 존재하는 SKU면 LEFT JOIN으로 GATH_DT가 NULL이 될 수 있으므로
        // 첫 번째 non-null 값을 찾는다.
        const snapshotDate = rows.find((r) => r.GATH_DT)?.GATH_DT ?? null;

        const whShipResult = await db
            .request()
            .input("cutoffDate", sql.VarChar, getPstCutoffDate(84))
            .query<WhShipRow>(WH_SHIP_84D_QUERY);

        const shipRatio84d: Record<string, ShipRatio84d> = {};
        for (const r of whShipResult.recordset) {
            const total = r.CA_QTY + r.TX_QTY + r.NJ_QTY + r.GA_QTY;
            if (total <= 0) continue;
            shipRatio84d[r.SKU] = {
                CA: r.CA_QTY / total,
                TX: r.TX_QTY / total,
                NJ: r.NJ_QTY / total,
                GA: r.GA_QTY / total,
            };
        }

        //console.log(shipRatio84d);

        return NextResponse.json({
            success: true,
            data: rows,
            snapshotDate,
            shipRatio84d,
        });
    } catch (err) {
        console.error("DB 조회 오류:", err);
        return NextResponse.json(
            { success: false, error: String(err) },
            { status: 500 }
        );
    }
}