import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import SidebarFilter from "@/components/sidebarFilters";

const sourceSansPro = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sourceSansPro.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-row antialiased ">
        <SidebarFilter></SidebarFilter>
        <div className="px-6 w-full">{children}</div>
      </body>
    </html>
  );
}
